spring.application.name=service-registry
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# Actuator ? expose health endpoint for Docker healthcheck
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
