# =============================================================================
# Recipe Delivery Platform - Full Cleanup + Observability Setup
# Run from repo root:  powershell -ExecutionPolicy Bypass -File setup.ps1
# =============================================================================

$ErrorActionPreference = "Continue"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-File($path, $lines) {
    $dir = Split-Path $path -Parent
    if ($dir -and !(Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    [System.IO.File]::WriteAllLines($path, $lines, $utf8NoBom)
    Write-Host "  Written: $path"
}

function Move-Safe($src, $dst) {
    if (Test-Path $src) {
        $dstDir = Split-Path $dst -Parent
        if ($dstDir -and !(Test-Path $dstDir)) { New-Item -ItemType Directory -Path $dstDir -Force | Out-Null }
        Move-Item -Path $src -Destination $dst -Force
        Write-Host "  Moved:   $src  ->  $dst"
    }
}

Write-Host ""
Write-Host "============================================================"
Write-Host " Recipe Delivery Platform - Repo Cleanup + Observability"
Write-Host "============================================================"
Write-Host ""

# Verify we are in the right folder
if (!(Test-Path "docker-compose.yml")) {
    Write-Host "ERROR: docker-compose.yml not found."
    Write-Host "Run this from the ROOT of your repo."
    Write-Host "Example:  cd C:\Users\Ayush\OneDrive\Desktop\2k26\Ecommerce"
    Read-Host "Press Enter to exit"
    exit 1
}

# =============================================================================
Write-Host "[1/7] Deleting junk files and folders..."
Write-Host ""

$junkDirs  = @(".idea", "src", "saga")
$junkFiles = @("git", "find_dbs.py", ".env", "order-service.zip", "payment-service.zip")

foreach ($d in $junkDirs) {
    if (Test-Path $d) { Remove-Item -Recurse -Force $d; Write-Host "  Deleted: $d\" }
}
foreach ($f in $junkFiles) {
    if (Test-Path $f) { Remove-Item -Force $f; Write-Host "  Deleted: $f" }
}

# =============================================================================
Write-Host ""
Write-Host "[2/7] Creating folder structure and moving services..."
Write-Host ""

# Create top-level folders
foreach ($d in @("services","infra\docker","infra\scripts","observability\prometheus",
                 "observability\grafana\provisioning\datasources",
                 "observability\grafana\provisioning\dashboards",
                 "observability\grafana\dashboards")) {
    if (!(Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null }
}

# Simple service moves (no double nesting)
foreach ($svc in @("api-gateway","service-registry","user-service","recipe-service","admin-service","payment-service")) {
    if ((Test-Path $svc) -and !(Test-Path "services\$svc")) {
        Move-Safe $svc "services\$svc"
    }
}

# Double-nested services - flatten them
foreach ($svc in @("inventory-service","order-service","notification-service")) {
    $nested = "$svc\$svc"
    if ((Test-Path $nested) -and !(Test-Path "services\$svc")) {
        Move-Safe $nested "services\$svc"
        Remove-Item -Recurse -Force $svc -ErrorAction SilentlyContinue
    } elseif ((Test-Path $svc) -and !(Test-Path "services\$svc")) {
        Move-Safe $svc "services\$svc"
    }
}

# Move docker\ -> infra\docker\
if (Test-Path "docker") {
    Copy-Item -Recurse -Force "docker\*" "infra\docker\"
    Remove-Item -Recurse -Force "docker"
    Write-Host "  Moved:   docker\  ->  infra\docker\"
}

# Move seed_data.py -> infra\scripts\
if (Test-Path "seed_data.py") { Move-Safe "seed_data.py" "infra\scripts\seed_data.py" }

Write-Host "  Done."

# =============================================================================
Write-Host ""
Write-Host "[3/7] Writing docker-compose.yml..."
Write-Host ""

$dockerCompose = @(
"networks:"
"  ecom-net:"
"    driver: bridge"
""
"volumes:"
"  postgres-data:"
"  redis-data:"
"  zookeeper-data:"
"  kafka-data:"
"  grafana-data:"
""
"services:"
""
"  # INFRASTRUCTURE"
""
"  postgres:"
"    image: postgres:16-alpine"
"    container_name: ecom-postgres"
"    restart: unless-stopped"
"    environment:"
"      POSTGRES_USER: `${POSTGRES_USER}"
"      POSTGRES_PASSWORD: `${POSTGRES_PASSWORD}"
"      POSTGRES_MULTIPLE_DATABASES: userDB,orderServiceDB,inventoryDB,paymentDB,recipeDB,adminDB"
"    volumes:"
"      - postgres-data:/var/lib/postgresql/data"
"      - ./infra/docker/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh:ro"
"    ports:"
"      - `"5432:5432`""
"    networks:"
"      - ecom-net"
"    healthcheck:"
"      test: [`"CMD-SHELL`", `"pg_isready -U postgres`"]"
"      interval: 10s"
"      timeout: 5s"
"      retries: 5"
""
"  redis:"
"    image: redis:7-alpine"
"    container_name: ecom-redis"
"    restart: unless-stopped"
"    volumes:"
"      - redis-data:/data"
"    ports:"
"      - `"6379:6379`""
"    networks:"
"      - ecom-net"
"    healthcheck:"
"      test: [`"CMD`", `"redis-cli`", `"ping`"]"
"      interval: 10s"
"      timeout: 5s"
"      retries: 5"
""
"  zookeeper:"
"    image: confluentinc/cp-zookeeper:7.6.0"
"    container_name: ecom-zookeeper"
"    restart: unless-stopped"
"    environment:"
"      ZOOKEEPER_CLIENT_PORT: 2181"
"      ZOOKEEPER_TICK_TIME: 2000"
"    volumes:"
"      - zookeeper-data:/var/lib/zookeeper/data"
"    ports:"
"      - `"2181:2181`""
"    networks:"
"      - ecom-net"
""
"  kafka:"
"    image: confluentinc/cp-kafka:7.6.0"
"    container_name: ecom-kafka"
"    restart: unless-stopped"
"    depends_on:"
"      - zookeeper"
"    environment:"
"      KAFKA_BROKER_ID: 1"
"      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181"
"      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
"      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
"      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT"
"      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1"
"      KAFKA_AUTO_CREATE_TOPICS_ENABLE: `"true`""
"    volumes:"
"      - kafka-data:/var/lib/kafka/data"
"    ports:"
"      - `"9092:9092`""
"    networks:"
"      - ecom-net"
""
"  # OBSERVABILITY"
""
"  prometheus:"
"    image: prom/prometheus:v2.51.0"
"    container_name: ecom-prometheus"
"    restart: unless-stopped"
"    volumes:"
"      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
"    ports:"
"      - `"9090:9090`""
"    networks:"
"      - ecom-net"
"    command:"
"      - '--config.file=/etc/prometheus/prometheus.yml'"
"      - '--storage.tsdb.retention.time=7d'"
""
"  grafana:"
"    image: grafana/grafana:10.4.0"
"    container_name: ecom-grafana"
"    restart: unless-stopped"
"    depends_on:"
"      - prometheus"
"    ports:"
"      - `"3000:3000`""
"    environment:"
"      - GF_SECURITY_ADMIN_USER=`${GRAFANA_ADMIN_USER:-admin}"
"      - GF_SECURITY_ADMIN_PASSWORD=`${GRAFANA_ADMIN_PASSWORD:-admin}"
"      - GF_USERS_ALLOW_SIGN_UP=false"
"    volumes:"
"      - grafana-data:/var/lib/grafana"
"      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro"
"      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro"
"    networks:"
"      - ecom-net"
""
"  # MICROSERVICES"
""
"  service-registry:"
"    build:"
"      context: ./services/service-registry"
"      dockerfile: Dockerfile"
"    container_name: ecom-service-registry"
"    restart: unless-stopped"
"    ports:"
"      - `"8761:8761`""
"    networks:"
"      - ecom-net"
"    environment:"
"      - SERVER_PORT=8761"
""
"  api-gateway:"
"    build:"
"      context: ./services/api-gateway"
"      dockerfile: Dockerfile"
"    container_name: ecom-api-gateway"
"    restart: unless-stopped"
"    depends_on:"
"      service-registry:"
"        condition: service_started"
"    ports:"
"      - `"8080:8080`""
"    networks:"
"      - ecom-net"
"    environment:"
"      - SERVER_PORT=8080"
"      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka"
"      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true"
"      - JWT_SECRET=`${JWT_SECRET}"
""
"  user-service:"
"    build:"
"      context: ./services/user-service"
"      dockerfile: Dockerfile"
"    container_name: ecom-user-service"
"    restart: unless-stopped"
"    depends_on:"
"      postgres:"
"        condition: service_healthy"
"      redis:"
"        condition: service_healthy"
"      service-registry:"
"        condition: service_started"
"    ports:"
"      - `"8084:8084`""
"    networks:"
"      - ecom-net"
"    environment:"
"      - SERVER_PORT=8084"
"      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/userDB"
"      - SPRING_DATASOURCE_USERNAME=`${POSTGRES_USER}"
"      - SPRING_DATASOURCE_PASSWORD=`${POSTGRES_PASSWORD}"
"      - SPRING_DATA_REDIS_HOST=redis"
"      - SPRING_DATA_REDIS_PORT=6379"
"      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka"
"      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true"
""
"  recipe-service:"
"    build:"
"      context: ./services/recipe-service"
"      dockerfile: Dockerfile"
"    container_name: ecom-recipe-service"
"    restart: unless-stopped"
"    depends_on:"
"      postgres:"
"        condition: service_healthy"
"      service-registry:"
"        condition: service_started"
"    ports:"
"      - `"8081:8081`""
"    networks:"
"      - ecom-net"
"    environment:"
"      - SERVER_PORT=8081"
"      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/recipeDB"
"      - SPRING_DATASOURCE_USERNAME=`${POSTGRES_USER}"
"      - SPRING_DATASOURCE_PASSWORD=`${POSTGRES_PASSWORD}"
"      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka"
"      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true"
""
"  inventory-service:"
"    build:"
"      context: ./services/inventory-service"
"      dockerfile: Dockerfile"
"    container_name: ecom-inventory-service"
"    restart: unless-stopped"
"    depends_on:"
"      postgres:"
"        condition: service_healthy"
"      service-registry:"
"        condition: service_started"
"      kafka:"
"        condition: service_started"
"    ports:"
"      - `"8082:8082`""
"    networks:"
"      - ecom-net"
"    environment:"
"      - SERVER_PORT=8082"
"      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/inventoryDB"
"      - SPRING_DATASOURCE_USERNAME=`${POSTGRES_USER}"
"      - SPRING_DATASOURCE_PASSWORD=`${POSTGRES_PASSWORD}"
"      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092"
"      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka"
"      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true"
"      - EUREKA_INSTANCE_HOSTNAME=ecom-inventory-service"
""
"  order-service:"
"    build:"
"      context: ./services/order-service"
"      dockerfile: Dockerfile"
"    container_name: ecom-order-service"
"    restart: unless-stopped"
"    depends_on:"
"      postgres:"
"        condition: service_healthy"
"      service-registry:"
"        condition: service_started"
"      kafka:"
"        condition: service_started"
"    ports:"
"      - `"8083:8083`""
"    networks:"
"      - ecom-net"
"    environment:"
"      - SERVER_PORT=8083"
"      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/orderServiceDB"
"      - SPRING_DATASOURCE_USERNAME=`${POSTGRES_USER}"
"      - SPRING_DATASOURCE_PASSWORD=`${POSTGRES_PASSWORD}"
"      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092"
"      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka"
"      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true"
""
"  payment-service:"
"    build:"
"      context: ./services/payment-service"
"      dockerfile: Dockerfile"
"    container_name: ecom-payment-service"
"    restart: unless-stopped"
"    depends_on:"
"      postgres:"
"        condition: service_healthy"
"      service-registry:"
"        condition: service_started"
"      kafka:"
"        condition: service_started"
"    ports:"
"      - `"8085:8085`""
"    networks:"
"      - ecom-net"
"    environment:"
"      - SERVER_PORT=8085"
"      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/paymentDB"
"      - SPRING_DATASOURCE_USERNAME=`${POSTGRES_USER}"
"      - SPRING_DATASOURCE_PASSWORD=`${POSTGRES_PASSWORD}"
"      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092"
"      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka"
"      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true"
""
"  notification-service:"
"    build:"
"      context: ./services/notification-service"
"      dockerfile: Dockerfile"
"    container_name: ecom-notification-service"
"    restart: unless-stopped"
"    depends_on:"
"      service-registry:"
"        condition: service_started"
"      kafka:"
"        condition: service_started"
"    ports:"
"      - `"8086:8086`""
"    networks:"
"      - ecom-net"
"    environment:"
"      - SERVER_PORT=8086"
"      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092"
"      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka"
"      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true"
"      - SPRING_MAIL_USERNAME=`${MAIL_USERNAME}"
"      - SPRING_MAIL_PASSWORD=`${MAIL_PASSWORD}"
"      - NOTIFICATION_MAIL_FROM=`${MAIL_FROM}"
""
"  admin-service:"
"    build:"
"      context: ./services/admin-service"
"      dockerfile: Dockerfile"
"    container_name: ecom-admin-service"
"    restart: unless-stopped"
"    depends_on:"
"      postgres:"
"        condition: service_healthy"
"      service-registry:"
"        condition: service_started"
"    ports:"
"      - `"8087:8087`""
"    networks:"
"      - ecom-net"
"    environment:"
"      - SERVER_PORT=8087"
"      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/adminDB"
"      - SPRING_DATASOURCE_USERNAME=`${POSTGRES_USER}"
"      - SPRING_DATASOURCE_PASSWORD=`${POSTGRES_PASSWORD}"
"      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka"
"      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true"
)
Write-File "docker-compose.yml" $dockerCompose

# =============================================================================
Write-Host ""
Write-Host "[4/7] Writing observability\prometheus\prometheus.yml..."
Write-Host ""

$prometheus = @(
"global:"
"  scrape_interval: 15s"
"  evaluation_interval: 15s"
"  external_labels:"
"    monitor: recipe-delivery-platform"
""
"scrape_configs:"
""
"  - job_name: prometheus"
"    static_configs:"
"      - targets: ['localhost:9090']"
""
"  - job_name: api-gateway"
"    metrics_path: /actuator/prometheus"
"    static_configs:"
"      - targets: ['api-gateway:8080']"
""
"  - job_name: service-registry"
"    metrics_path: /actuator/prometheus"
"    static_configs:"
"      - targets: ['service-registry:8761']"
""
"  - job_name: user-service"
"    metrics_path: /actuator/prometheus"
"    static_configs:"
"      - targets: ['user-service:8084']"
""
"  - job_name: recipe-service"
"    metrics_path: /actuator/prometheus"
"    static_configs:"
"      - targets: ['recipe-service:8081']"
""
"  - job_name: inventory-service"
"    metrics_path: /actuator/prometheus"
"    static_configs:"
"      - targets: ['inventory-service:8082']"
""
"  - job_name: order-service"
"    metrics_path: /actuator/prometheus"
"    static_configs:"
"      - targets: ['order-service:8083']"
""
"  - job_name: payment-service"
"    metrics_path: /actuator/prometheus"
"    static_configs:"
"      - targets: ['payment-service:8085']"
""
"  - job_name: notification-service"
"    metrics_path: /actuator/prometheus"
"    static_configs:"
"      - targets: ['notification-service:8086']"
""
"  - job_name: admin-service"
"    metrics_path: /actuator/prometheus"
"    static_configs:"
"      - targets: ['admin-service:8087']"
)
Write-File "observability\prometheus\prometheus.yml" $prometheus

# =============================================================================
Write-Host ""
Write-Host "[5/7] Writing Grafana provisioning files..."
Write-Host ""

$datasource = @(
"apiVersion: 1"
""
"datasources:"
"  - name: Prometheus"
"    type: prometheus"
"    access: proxy"
"    url: http://prometheus:9090"
"    isDefault: true"
"    editable: false"
"    jsonData:"
"      timeInterval: 15s"
"      httpMethod: POST"
)
Write-File "observability\grafana\provisioning\datasources\datasource.yml" $datasource

$dashboardProvider = @(
"apiVersion: 1"
""
"providers:"
"  - name: Recipe Delivery Platform"
"    orgId: 1"
"    folder: Microservices"
"    type: file"
"    disableDeletion: false"
"    editable: true"
"    updateIntervalSeconds: 30"
"    allowUiUpdates: true"
"    options:"
"      path: /var/lib/grafana/dashboards"
)
Write-File "observability\grafana\provisioning\dashboards\dashboards.yml" $dashboardProvider

# =============================================================================
Write-Host ""
Write-Host "[6/7] Writing .env.example and .gitignore..."
Write-Host ""

$envExample = @(
"# ---------------------------------------------------------------------------"
"# Recipe Delivery Platform - Environment Variables Template"
"# 1. Copy this file:  copy .env.example .env"
"# 2. Fill in your real values in .env"
"# 3. NEVER commit .env to git"
"# ---------------------------------------------------------------------------"
""
"# PostgreSQL"
"POSTGRES_USER=postgres"
"POSTGRES_PASSWORD=your_strong_password_here"
""
"# Notification Service (Gmail SMTP)"
"# Generate App Password: Google Account > Security > App Passwords"
"MAIL_USERNAME=your_email@gmail.com"
"MAIL_PASSWORD=your_gmail_app_password_here"
"MAIL_FROM=RecipeEcom <your_email@gmail.com>"
""
"# API Gateway JWT (must be 64 hex characters = 256 bits)"
"JWT_SECRET=your_256bit_hex_secret_here"
""
"# Grafana"
"GRAFANA_ADMIN_USER=admin"
"GRAFANA_ADMIN_PASSWORD=choose_a_secure_password"
)
Write-File ".env.example" $envExample

$gitignore = @(
"# Secrets"
".env"
""
"# IntelliJ"
".idea/"
"*.iml"
""
"# VS Code"
".vscode/"
""
"# Java / Maven"
"target/"
"*.class"
"*.jar"
"*.war"
"*.log"
""
"# OS"
".DS_Store"
"Thumbs.db"
""
"# Archives"
"*.zip"
"*.tar.gz"
""
"# Docker local volumes"
"postgres-data/"
"grafana-data/"
""
"# Python"
"__pycache__/"
"*.pyc"
)
Write-File ".gitignore" $gitignore

# =============================================================================
Write-Host ""
Write-Host "[7/7] Staging all changes in git..."
Write-Host ""

git add -A
git status

Write-Host ""
Write-Host "============================================================"
Write-Host " ALL DONE! Next steps:"
Write-Host ""
Write-Host " 1. Copy microservices-overview.json into:"
Write-Host "    observability\grafana\dashboards\"
Write-Host ""
Write-Host " 2. Add actuator + micrometer to each service pom.xml"
Write-Host " 3. Add management: block to each service application.yml"
Write-Host ""
Write-Host " 4. Create your .env file:"
Write-Host "    copy .env.example .env"
Write-Host "    (then fill in real values)"
Write-Host ""
Write-Host " 5. Commit:"
Write-Host "    git commit -m refactor-clean-structure-observability"
Write-Host "    git push"
Write-Host ""
Write-Host " 6. Remove .env from git history (run once):"
Write-Host "    git filter-branch --force --index-filter"
Write-Host "    git rm --cached --ignore-unmatch .env"
Write-Host "    --prune-empty --tag-name-filter cat -- --all"
Write-Host "    git push --force"
Write-Host ""
Write-Host " 7. Revoke your Gmail App Password at myaccount.google.com!"
Write-Host "============================================================"
Write-Host ""
Read-Host "Press Enter to exit"
