spring.application.name=payment-service
server.port=8085

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/paymentDB
spring.datasource.username=postgres
spring.datasource.password=Ayush@0943
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.api.key=${STRIPE_API_KEY}

# Default currency for all payments
stripe.currency=INR

# Stripe webhook secret (for verifying webhook events from Stripe dashboard)
#stripe.webhook.secret=whsec_your_webhook_secret_here
